# standard yml for building a lab server

---
- hosts: centos7
  remote_user: root
  become: true
  become_user: root

  tasks:

  - name: Run update
    yum:
      name: "*"
      state: latest

  - name: Disable selinux
    selinux:
      state: disabled

  - name: Disable firewalld
    service:
      name: firewalld
      enabled: no

  - name: Install ntp if this is a physical host
    when: ansible_virtualization_role == "host"
    yum:
      name: ntp
      state: latest

  - name: create ntp conf
    when: ansible_virtualization_role == "host"
    local_action: copy content="server {{ NTP_SERVER_IP }} driftfile /var/lib/ntp/drift" dest="/tmp/testfile"

  - name: copy ntp conf to server
    when: ansible_virtualization_role == "host"
    copy:
      src: /tmp/testfile
      dest: /etc/ntp.conf
      owner: root
      group: root
      mode: 0644

  - name: Install open vm tools if this is a virtual machine
    when: ansible_virtualization_role == "guest"
    yum:
      name: open-vm-tools
      state: latest

  - name: Install common packages
    yum:
      name: "{{ packages }}"
    vars:
      packages:
      - bind-utils
      - cifs-utils
      - curl
      - epel-release
      - net-tools
      - nfs-utils
      - rsync
      - samba-client
      - wget

