---
#
# Common settings for Centos/Ubuntu test lab hosts
#
- hosts: '*'
  remote_user: root
  become: true
  become_user: root

  tasks:

  - name: Disable IPv6 with sysctl
    sysctl: name={{ item }} value=1 state=present reload=yes
    with_items:
      - net.ipv6.conf.all.disable_ipv6
      - net.ipv6.conf.default.disable_ipv6
      - net.ipv6.conf.lo.disable_ipv6
    when: ansible_facts['os_family'] == 'Debian' or ansible_facts['os_family'] == 'RedHat'

  - name: Disable IPv6 autoconf with sysctl
    sysctl: name={{ item }} value=0 state=present reload=yes
    with_items:
      - net.ipv6.conf.all.autoconf
      - net.ipv6.conf.default.autoconf
      - net.ipv6.conf.lo.autoconf
    when: ansible_facts['os_family'] == 'Debian' or ansible_facts['os_family'] == 'RedHat'

  - name: Check for selinux config
    stat: 
      path: /etc/selinux/config
    register: config_file 

  - name: Disable selinux
    selinux:
      state: disabled
    when: config_file.stat.exists

  - name: Add the user "{{ lab_username }}" 
    ansible.builtin.user:
      name: "{{ lab_username }}"
      password: "{{ lab_password }}" 
      shell: /bin/bash

  - name: Include CentOS Packages/Tasks
    include_tasks: centos_tasks.yml
    when: ansible_facts['os_family'] == 'RedHat'

  - name: Include Ubuntu Packages/Tasks
    include_tasks: ubuntu_tasks.yml
    when: ansible_facts['os_family'] == 'Debian'





