---
#
# Common settings for Centos/Ubuntu test lab hosts
#
- hosts: '*'
  remote_user: root
  become: true
  become_user: root

  tasks:

  - include_vars: group_vars/all/vault

  - name: Disable IPV6
    include: tasks/update_packages.yml

  - name: Disable IPV6
    include: tasks/disable_ipv6.yml

  - name: Disable Firewall 
    include: tasks/disable_firewall.yml

  - name: Disable selinux 
    include: tasks/disable_selinux.yml

  - name: Install Open VMWare Tools 
    include: tasks/install_vmware_tools.yml

  - name: Install Centos/Redhat Packages 
    include: tasks/install_redhat_packages.yml
    when: ansible_facts['os_family'] == 'RedHat'

  - name: Install Ubuntu/Debian Packages 
    include: tasks/install_ubuntu_packages.yml
    when: ansible_facts['os_family'] == 'Debian'

  - name: Add Users 
    include: tasks/users.yml

  - name: Ssh Configuration 
    include: tasks/ssh.yml


  - name: Configure NTP 
    include: tasks/ntp_config.yml

#  - name: Add the user "{{ lab_username }}" 
#    ansible.builtin.user:
#      name: "{{ lab_username }}"
#      password: "{{ lab_password }}" 
#      shell: /bin/bash
#
#  - name: Include CentOS Packages/Tasks
#    include_tasks: centos_tasks.yml
#    when: ansible_facts['os_family'] == 'RedHat'
#
#  - name: Include Ubuntu Packages/Tasks
#    include_tasks: ubuntu_tasks.yml
#    when: ansible_facts['os_family'] == 'Debian'
#
#
#
#
#
