#
# playbook for installing software on my workstation
#
---
- hosts: mint
  become: yes
  remote_user: root
  become_user: root

  tasks:

    - name: Add google key
      apt_key:
        url: https://dl.google.com/linux/linux_signing_key.pub
        state: present

    - name: Add google repo
      apt_repository:
        state: present
        repo: deb http://dl.google.com/linux/chrome/deb/ stable main

    - name: Update and Upgrade
      apt:
        update_cache: yes
        upgrade: dist

    - name: Install Packages
      apt:
        pkg:
        - arp-scan
        - avahi-utils
        - brasero
        - google-chrome-stable
        - autoconf
        - automake
        - awscli
        - cifs-utils
        - dnsutils
        - fping
        - g++
        - golang-go
        - gradle
        - ipcalc
        - iperf
        - iptraf-ng
        - iputils-arping
        - iputils-ping
        - iputils-tracepath
        - maven
        - ncftp
        - net-tools
        - nfs-common
        - nfs-kernel-server
        - nmap
        - ntopng
        - nodejs
        - pylint
        - python3-minimal
        - python3-apport
        - python3-apt
        - python3-aptdaemon
        - python3-aptdaemon.gtk3widgets
        - python3
        - python3-brlapi
        - python3-bs4
        - python3-cairo
        - python3-certifi
        - python3-cffi-backend
        - python3-chardet
        - python3-commandnotfound
        - python3-configobj
        - python3-crypto
        - python3-cups
        - python3-cupshelpers
        - python3-dbus
        - python3-debian
        - python3-defer
        - python3-dev
        - python3-gdbm
        - python3-gi
        - python3-gi-cairo
        - python3-httplib2
        - python3-icu
        - python3-idna
        - python3-louis
        - python3-macaroonbakery
        - python3-mako
        - python3-markupsafe
        - python3-minimal
        - python3-nacl
        - python3-pam
        - python3-pexpect
        - python3-pil
        - python3-pip
        - python3-pkg-resources
        - python3-problem-report
        - python3-protobuf
        - python3-psutil
        - python3-ptyprocess
        - python3-pyatspi
        - python3-pycurl
        - python3-pyinotify
        - python3-pymacaroons
        - python3-pytest
        - python3-reportlab-accel
        - python3-reportlab
        - python3-requests
        - python3-requests-unixsocket
        - python3-rfc3339
        - python3-rrdtool
        - python3-scapy
        - python3-setproctitle
        - python3-six
        - python3-speechd
        - python3-systemd
        - python3-tz
        - python3-uno
        - python3-urllib3
        - python3-xapp
        - python3-xdg
        - python3-xkit
        - python3-xlib
        - python3-yaml
        - rsync
        - samba-common-bin
        - samba-common
        - samba-libs
        - sane-utils
        - snmp
        - snmpd
        - snmp-mibs-downloader
        - snmptrapd
        - sqlite3
        - sqlite
        - syncthing
        - tcpdump
        - telnet
        - tftp
        - traceroute
        - unzip
        - vagrant
        - virt-manager
        - virtualbox
        - wget
        - whois
        - wireshark
        - zip
    
    - name: Install Snaps
      snap:
        classic: yes
        name:
          - slack 
          - eclipse
          - code
          - pycharm-community 
          - intellij-idea-community 


# wget https://zoom.us/client/latest/zoom_amd64.deb
# sudo apt install ./zoom_amd64.deb
# disable firewall
# disable se linux
