

---
- hosts: ubuntu18:ubuntu20 
  become: yes
  remote_user: root
  become_user: root


  tasks:

  - include_vars: secrets.yml

  - name: Add user and groups for the lab user
    user:
      name: lab
      groups: sudo  
      password: "{{ lab_user_password }}" 
      append: yes

  - name: Change root's password 
    user:
      name: root 
      password: "{{ root_user_password }}"

  - name: Disable the firewall
    ufw:
      state: disabled

  - name: Run Apt Update
    apt:
      name: "*"
      update_cache: yes
      state: latest

  - name: Install open vm tools if this is a virtual machine
    when: ansible_virtualization_role == "guest"
    apt:
      name: open-vm-tools
      state: latest

  - name: Install Common Packages
    apt:
      pkg:
      - net-tools
      - avahi-utils 
      - avahi-daemon 
      - nfs-common

  - name: Disable ipv6 
    lineinfile:
      path: /etc/sysctl.conf
      line: net.ipv6.conf.all.disable_ipv6 = 1

  - name: Disable ipv6 
    lineinfile:
      path: /etc/sysctl.conf
      line: net.ipv6.conf.default.disable_ipv6 = 1

  - name: Disable ipv6 
    lineinfile:
      path: /etc/sysctl.conf
      line: net.ipv6.conf.lo.disable_ipv6 = 1

  - name: Check for selinux config
    stat:
      path: /etc/selinux/config
    register: config_file

  - name: Disable selinux
    selinux:
      state: disabled
    when: config_file.stat.exists

  - name: Sshd Config
    copy:
      src: assets/ubuntu/sshd_config
      dest: /etc/ssh/sshd_config
      owner: root
      group: root
      mode: u=rw,g=r,o=r

  - name: Create NFS directory for lab share
    file:
      path: /share/nfs
      state: directory
      mode: '0777'

  - name: Mount Shared Lab NFS
    mount:
      src: 10.80.0.72:/share/nfs
      path: /share/nfs
      opts: rw,sync
      state: mounted
      fstype: nfs

  - name: Create NFS directory for sw release
    file:
      path: Kwikbit-60GHz 
      state: directory
      mode: '0755'

  - name: Mount KB Releases
    mount:
      src: 192.168.0.42:/home/kwikbit/Kwikbit-60GHz
      path: /Kwikbit-60GHz
      opts: ro
      state: mounted
      fstype: nfs

  - name: Create NFS directory for tftp
    file:
      path: /tftp 
      state: directory
      mode: '0755'

  - name: Mount TFTP
    mount:
      src: 192.168.0.42:/var/tftp_dir
      path: /tftp
      opts: ro
      state: mounted
      fstype: nfs

