---
  - name: Disable ipv6 
    lineinfile:
      path: /etc/sysctl.conf
      line: net.ipv6.conf.all.disable_ipv6 = 1
    when: ansible_facts['os_family'] == 'Debian' or ansible_facts['os_family'] == 'RedHat'

  - name: Disable ipv6 
    lineinfile:
      path: /etc/sysctl.conf
      line: net.ipv6.conf.default.disable_ipv6 = 1
    when: ansible_facts['os_family'] == 'Debian' or ansible_facts['os_family'] == 'RedHat'

  - name: Disable ipv6 
    lineinfile:
      path: /etc/sysctl.conf
      line: net.ipv6.conf.lo.disable_ipv6 = 1
    when: ansible_facts['os_family'] == 'Debian' or ansible_facts['os_family'] == 'RedHat'

