---
  - name: Install Common Centos/Redhat Packages
    yum:
      name: "{{ packages }}"
    vars:
      packages:
      - epel-release
      - arp-scan
      - bind-utils
      - cifs-utils
      - curl
      - fping
      - iperf3
      - iputils
      - net-tools
      - nfs-utils
      - nmap
      - rsync
      - samba-client
      - tcpdump
      - telnet
      - tftp
      - traceroute
      - wget
      - whois
      - wireshark
