---
  - name: Sshd Config
    copy:
      src: assets/ubuntu/sshd_config
      dest: /etc/ssh/sshd_config
      owner: root
      group: root
      mode: u=rw,g=r,o=r
    when: ansible_facts['os_family'] == 'Debian'

  - name: Sshd Config
    copy:
      src: assets/redhat/sshd_config
      dest: /etc/ssh/sshd_config
      owner: root
      group: root
      mode: u=rw,g=r,o=r
    when: ansible_facts['os_family'] == 'RedHat'
