Vagrant.configure("2") do |config|


  config.vm.box = "bento/ubuntu-20.04"

  config.vm.network "public_network", bridge: "wlp58s0"

  config.vm.provision "file", source: "../assets/sshd_config", destination: "/tmp/sshd_config"
  config.vm.provision "file", source: "~/.ssh/id_ecdsa.pub", destination: "/tmp/authorized_keys"
  config.vm.provision "file", source: "./setup.sh", destination: "/tmp/setup.sh"
  config.vm.provision "shell", inline: "bash /tmp/setup.sh", privileged: true


end
